name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-iamge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push external image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/msa-crawling-external ./external
          docker push ${{ secrets.DOCKER_USERNAME }}/msa-crawling-external:latest

      - name: Build and push univ image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/msa-crawling-univ ./univ
          docker push ${{ secrets.DOCKER_USERNAME }}/msa-crawling-univ:latest
